build:
  nodes:
    coverage:
      tests:
        override:
          - command: composer test
            coverage:
              file: build/coverage/log/coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

filter:
    excluded_paths:
        - 'test/*'
        - 'vendor/*'
